# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1VSyuSswMAXTQG41gZKNCuGdUO33ClFaF
"""

# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# 上传 CSV 文件
uploaded = files.upload()
# 假设文件名是你上传的 CSV 文件
data = pd.read_csv('KKK.csv')

# 查看前几行
data.head()


plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='imd_Value', data=data)
plt.title('Cultural Access vs IMD Deprivation in London')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('IMD Deprivation')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# 上传 CSV 文件
uploaded = files.upload()

# 假设文件名是你上传的 CSV 文件
data = pd.read_csv('KKKk.csv')

# 查看前几行
data.head()

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='imd_Value', data=data)
plt.title('Cultural Access vs IMD Deprivation')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('IMD Deprivation')
plt.show()


features = ['pre cultur', 'imd_Value']  # 要分析的列
scaler = StandardScaler()
data_scaled = scaler.fit_transform(data[features])

pca = PCA(n_components=2)
pca_result = pca.fit_transform(data_scaled)
data['PC1'] = pca_result[:,0]
data['PC2'] = pca_result[:,1]

plt.figure(figsize=(8,6))
sns.scatterplot(x='PC1', y='PC2', data=data)
plt.title('PCA of Cultural Access and IMD Deprivation')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.show()

k = 5  # 设置簇数量，可调整
kmeans = KMeans(n_clusters=k, random_state=0)
data['Cluster'] = kmeans.fit_predict(data_scaled)

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='imd_Value', hue='Cluster', palette='Set1', data=data)
plt.title('K-Means Clustering of Cultural Access & IMD Deprivation')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('IMD Deprivation')
plt.legend(title='Cluster')
plt.show()


kmeans_pca = KMeans(n_clusters=k, random_state=0)
data['Cluster_PCA'] = kmeans_pca.fit_predict(pca_result)

plt.figure(figsize=(8,6))
sns.scatterplot(x='PC1', y='PC2', hue='Cluster_PCA', palette='Set2', data=data)
plt.title('K-Means Clustering on PCA Components')
plt.xlabel('PC1')
plt.ylabel('PC2')
plt.show()

"""import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图更清晰
sns.set(style='whitegrid', font_scale=1.2)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

sns.set(style='whitegrid', font_scale=1.2)

data = pd.read_csv("KKKZRX.csv")
print("数据预览：")
display(data.head())



# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# 上传 CSV 文件
uploaded = files.upload()
# 假设文件名是你上传的 CSV 文件
data = pd.read_csv('KKK.csv')

# 查看前几行
data.head()

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='lsoa-data_Qualifications;Highest level of qualification: Level 4 qualifications and above;2011', data=data)
plt.title('Cultural Access vs Education Rate in London')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('Education Rate (%)')
plt.show()



# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# 上传 CSV 文件
uploaded = files.upload()
# 假设文件名是你上传的 CSV 文件
data = pd.read_csv('KKK.csv')

# 查看前几行
data.head()

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='lsoa-data_Qualifications;Highest level of qualification: Level 4 qualifications and above;2011', data=data)
plt.title('Cultural Access vs Education Rate in London')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('Education Rate (%)')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# 导入所需库
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.cluster import KMeans

# 让图直接显示在 Notebook 中
# %matplotlib inline
from google.colab import files

# 上传 CSV 文件
uploaded = files.upload()
# 假设文件名是你上传的 CSV 文件
data = pd.read_csv('KKK.csv')

# 查看前几行
data.head()

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='imd_Value', data=data)
plt.title('Cultural Access vs Education Rate in London')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('IMD Deprivation')
plt.show()

plt.figure(figsize=(8,6))
sns.scatterplot(x='pre cultur', y='lsoa-data_Qualifications;Highest level of qualification: Level 4 qualifications and above;2011', data=data)
plt.title('Cultural Access vs Education Rate in London')
plt.xlabel('Per Capita Cultural Value')
plt.ylabel('Education Rate (%)')
plt.show()